# Generated by Django 4.2.24 on 2025-10-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('tipo_movimiento', models.CharField(choices=[('COMPRA_PROVEEDOR', 'Compra a Proveedor'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('CORRECCION_ERROR', 'Corrección de Error'), ('VENTA', 'Venta'), ('MERMA', 'Merma/Deterioro'), ('DANO', 'Producto Dañado'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('RESERVA', 'Reserva de Stock'), ('LIBERACION_RESERVA', 'Liberación de Reserva')], max_length=30, verbose_name='Tipo de movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
