# Generated by Django 4.2.24 on 2025-10-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('COMPRA_PROVEEDOR', 'Compra a Proveedor'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('CORRECCION_ERROR', 'Corrección de Error'), ('VENTA', 'Venta'), ('MERMA', 'Merma/Deterioro'), ('DANO', 'Producto Dañado'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('RESERVA', 'Reserva de Stock'), ('LIBERACION_RESERVA', 'Liberación de Reserva')], max_length=30, verbose_name='Tipo de movimiento'),
        ),
    ]
