# Generated by Django 4.2.24 on 2025-10-20 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
    ]
