# Generated by Django 4.2.24 on 2025-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('tipo_notificacion', models.CharField(choices=[('RECORDATORIO_PREVIO', 'Recordatorio 3 días antes'), ('VENCIMIENTO', 'Notificación de vencimiento'), ('MORA_1', 'Primera notificación de mora (15 días)'), ('MORA_2', 'Segunda notificación de mora (30 días)'), ('MORA_3', 'Tercera notificación de mora (45 días)'), ('MORA_4', 'Cuarta notificación de mora (60 días)'), ('ACCION_LEGAL', 'Quinta notificación - Acciones legales')], max_length=30, verbose_name='Tipo de notificación')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('email_destinatario', models.EmailField(max_length=254, verbose_name='Email destinatario')),
                ('enviado_exitosamente', models.BooleanField(default=False, verbose_name='Enviado exitosamente')),
                ('error_envio', models.TextField(blank=True, null=True, verbose_name='Error de envío')),
            ],
            options={
                'verbose_name': 'Notificación de Pago',
                'verbose_name_plural': 'Notificaciones de Pago',
                'db_table': 'notificaciones_pago',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto pagado')),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado del pago')),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], max_length=20, verbose_name='Método de pago')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia/Comprobante')),
                ('fecha_pago', models.DateTimeField(verbose_name='Fecha de pago')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
