# Generated by Django 4.2.24 on 2025-10-10 14:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notificacionpago',
            managers=[
                ('activos', django.db.models.manager.Manager()),
            ],
        ),
    ]
