# Generated by Django 4.2.24 on 2025-10-20 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pagos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.AddField(
            model_name='notificacionpago',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_pago', to='Pedidos.pedido', verbose_name='Pedido'),
        ),
    ]
