# Generated by Django 4.2.24 on 2025-10-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'detalles_pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('estado_pedido', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGO_CONFIRMADO', 'Pago Confirmado'), ('EN_DESPACHO', 'En Despacho'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_PAGO', max_length=30, verbose_name='Estado del pedido')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Número de orden')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('tipo_pago', models.CharField(choices=[('INMEDIATO', 'Pago Inmediato'), ('DIFERIDO', 'Pago Diferido')], default='INMEDIATO', max_length=20, verbose_name='Tipo de pago')),
                ('fecha_limite_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite de pago')),
                ('pago_diferido_aprobado', models.BooleanField(default=False, verbose_name='Pago diferido aprobado')),
                ('fecha_aprobacion_pago_diferido', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación pago diferido')),
                ('factura_enviada', models.BooleanField(default=False, verbose_name='Factura enviada')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
