# Generated by Django 4.2.24 on 2025-10-20 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Solicitudes', '0001_initial'),
        ('Empresas', '0002_initial'),
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aprobador_pago_diferido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_diferidos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobador pago diferido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='Empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='Solicitudes.solicitud', verbose_name='Solicitud origen'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='Productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together={('pedido', 'producto')},
        ),
    ]
