# Generated by Django 4.2.24 on 2025-10-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PAGO_CONFIRMADO', 'Pago Confirmado'), ('EN_DESPACHO', 'En Despacho'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_PAGO', max_length=30, verbose_name='Estado del pedido'),
        ),
    ]
