# Generated by Django 4.2.24 on 2025-10-09 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pedidos', '0002_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aprobador_pago_diferido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_diferidos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobador pago diferido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_aprobacion_pago_diferido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación pago diferido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_limite_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite de pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago_diferido_aprobado',
            field=models.BooleanField(default=False, verbose_name='Pago diferido aprobado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(choices=[('INMEDIATO', 'Pago Inmediato'), ('DIFERIDO', 'Pago Diferido')], default='INMEDIATO', max_length=20, verbose_name='Tipo de pago'),
        ),
    ]
