# Generated by Django 4.2.24 on 2025-10-10 14:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0003_pedido_aprobador_pago_diferido_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='detallepedido',
            managers=[
                ('activos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='factura_enviada',
            field=models.BooleanField(default=False, verbose_name='Factura enviada'),
        ),
    ]
