# Generated by Django 4.2.24 on 2025-10-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0004_alter_detallepedido_managers_pedido_factura_enviada'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='detallepedido',
            managers=[
            ],
        ),
    ]
