# Generated by Django 4.2.24 on 2025-10-20 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código del permiso')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre descriptivo')),
                ('modulo', models.CharField(choices=[('pedidos', 'Pedidos'), ('solicitudes', 'Solicitudes'), ('usuarios', 'Usuarios'), ('productos', 'Productos'), ('inventario', 'Inventario'), ('reportes', 'Reportes'), ('pagos', 'Pagos'), ('empresas', 'Empresas')], max_length=50, verbose_name='Módulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'ordering': ['modulo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('SISTEMA', 'Rol del Sistema'), ('PERSONALIZADO', 'Rol Personalizado')], default='PERSONALIZADO', max_length=20, verbose_name='Tipo de rol')),
                ('es_modificable', models.BooleanField(default=True, help_text='Los roles del sistema base no son modificables (pero se pueden clonar)', verbose_name='¿Es modificable?')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('cargo', models.CharField(default='Sin cargo', max_length=100, verbose_name='Cargo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿Es staff?')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('token_activacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token de activación')),
                ('token_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del token')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='Empresas.area', verbose_name='Área')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='Empresas.empresa', verbose_name='Empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('roles', models.ManyToManyField(blank=True, related_name='usuarios', to='Usuarios.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='role',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='NULL para roles del sistema, empresa específica para roles personalizados', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='Empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='role',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles', to='Usuarios.permiso', verbose_name='Permisos'),
        ),
    ]
