# Generated by Django 4.2.24 on 2025-10-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nombre'], 'permissions': (('ver_areas_empresa', 'Puede ver áreas de su empresa'), ('crear_area', 'Puede crear áreas'), ('editar_area', 'Puede editar áreas')), 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'permissions': (('ver_todas_empresas', 'Puede ver todas las empresas'), ('crear_empresa', 'Puede crear empresas'), ('editar_empresa', 'Puede editar empresas'), ('autorizar_pago_diferido', 'Puede autorizar pago diferido')), 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-date_joined'], 'permissions': (('ver_usuarios_empresa', 'Puede ver usuarios de su empresa'), ('crear_usuario_empresa', 'Puede crear usuarios en su empresa'), ('editar_usuario_empresa', 'Puede editar usuarios de su empresa'), ('asignar_permisos_validador', 'Puede asignar permisos de validador'), ('gestionar_todos_usuarios', 'Puede gestionar todos los usuarios del sistema')), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
