# Generated by Django 4.2.24 on 2025-10-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_admin_empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_admin_sistema',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_solicitante',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_validador_abastecimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_validador_financiero',
        ),
    ]
