# Generated by Django 4.2.24 on 2025-10-16 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoriaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('accion', models.CharField(choices=[('ASIGNAR', 'Asignar Grupo'), ('REMOVER', 'Remover Grupo')], max_length=20, verbose_name='Acción')),
                ('grupo_nombre', models.CharField(max_length=100, verbose_name='Nombre del grupo')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo del cambio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_grupos', to='Empresas.empresa', verbose_name='Empresa')),
                ('usuario_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones_grupos_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario afectado')),
                ('usuario_modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_grupos_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría de Grupo',
                'verbose_name_plural': 'Registros de Auditoría de Grupos',
                'db_table': 'auditoria_grupos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
