# Generated by Django 4.2.24 on 2025-10-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(default='Sin cargo', max_length=100, verbose_name='Cargo'),
        ),
    ]
