# Generated by Django 4.2.24 on 2025-10-10 14:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_categoria_options_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='categoria',
            managers=[
                ('activos', django.db.models.manager.Manager()),
            ],
        ),
    ]
