# Generated by Django 4.2.24 on 2025-10-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_categoria_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='categoria',
            managers=[
            ],
        ),
    ]
