# Generated by Django 4.2.24 on 2025-10-06 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0004_alter_empresa_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Productos', '0002_alter_categoria_options_alter_producto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('estado_solicitud', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADA_FINANCIERO', 'Validada por Financiero'), ('VALIDADA_ABASTECIMIENTO', 'Validada por Abastecimiento'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=30, verbose_name='Estado de la solicitud')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones generales')),
                ('fecha_validacion_financiero', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación financiera')),
                ('observaciones_financiero', models.TextField(blank=True, null=True, verbose_name='Observaciones del validador financiero')),
                ('fecha_validacion_abastecimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación de abastecimiento')),
                ('observaciones_abastecimiento', models.TextField(blank=True, null=True, verbose_name='Observaciones del validador de abastecimiento')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='Empresas.area', verbose_name='Área')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='Empresas.empresa', verbose_name='Empresa')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('validador_abastecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_abastecimiento', to=settings.AUTH_USER_MODEL, verbose_name='Validador de Abastecimiento')),
                ('validador_financiero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_financieras', to=settings.AUTH_USER_MODEL, verbose_name='Validador Financiero')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitudes',
                'ordering': ['-fecha_creacion'],
                'permissions': [('validar_financiero', 'Puede validar solicitudes financieramente'), ('validar_abastecimiento', 'Puede validar solicitudes de abastecimiento')],
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad solicitada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_solicitud', to='Productos.producto', verbose_name='Producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitud',
                'db_table': 'detalles_solicitud',
                'ordering': ['id'],
                'unique_together': {('solicitud', 'producto')},
            },
        ),
    ]
