# Generated by Django 4.2.24 on 2025-10-15 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Solicitudes', '0001_initial'),
        ('Productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='validador_abastecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_abastecimiento', to=settings.AUTH_USER_MODEL, verbose_name='Validador de Abastecimiento'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='validador_financiero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones_financieras', to=settings.AUTH_USER_MODEL, verbose_name='Validador Financiero'),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_solicitud', to='Productos.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Solicitudes.solicitud', verbose_name='Solicitud'),
        ),
        migrations.AlterUniqueTogether(
            name='detallesolicitud',
            unique_together={('solicitud', 'producto')},
        ),
    ]
