# Generated by Django 4.2.24 on 2025-10-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0002_alter_solicitud_estado_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('PENDIENTE_ABASTECIMIENTO', 'Pendiente de Validación Abastecimiento'), ('PENDIENTE_FINANZAS', 'Pendiente de Validación Financiera'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE_ABASTECIMIENTO', max_length=30, verbose_name='Estado de la solicitud'),
        ),
    ]
