# Generated by Django 4.2.24 on 2025-10-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0003_alter_solicitud_estado_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.CharField(choices=[('PENDIENTE_ABASTECIMIENTO', 'Pendiente de Validación Abastecimiento'), ('PENDIENTE_FINANZAS', 'Pendiente de Validación Financiera'), ('LISTO_PARA_COMPRA', 'Listo para Compra'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE_ABASTECIMIENTO', max_length=30, verbose_name='Estado de la solicitud'),
        ),
    ]
