# Generated by Django 4.2.24 on 2025-10-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0005_alter_detallesolicitud_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='detallesolicitud',
            managers=[
            ],
        ),
    ]
