# Generated by Django 4.2.24 on 2025-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('es_area_financiera', models.BooleanField(default=False, help_text='Marca si esta área corresponde al departamento financiero', verbose_name='¿Es área financiera?')),
                ('es_area_abastecimiento', models.BooleanField(default=False, help_text='Marca si esta área corresponde al departamento de abastecimiento', verbose_name='¿Es área de abastecimiento?')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('sector', models.CharField(max_length=100, verbose_name='Sector')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('nombre_contacto', models.CharField(default='Sin contacto', max_length=200, verbose_name='Nombre del contacto')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo de contacto')),
                ('pagar_despues', models.BooleanField(default=False, verbose_name='¿Autorizado para pago diferido?')),
                ('periodo_pago_dias', models.IntegerField(default=60, help_text='Máximo 60 días (2 meses)', verbose_name='Periodo máximo de pago (días)')),
                ('token_activacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token de activación')),
                ('token_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del token')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['nombre'],
            },
        ),
    ]
