# Generated by Django 4.2.24 on 2025-10-03 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('sector', models.CharField(max_length=100, verbose_name='Sector')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo de contacto')),
                ('pagar_despues', models.BooleanField(default=False, verbose_name='¿Autorizado para pago diferido?')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['nombre'],
                'permissions': (('ver_todas_empresas', 'Puede ver todas las empresas'), ('crear_empresa', 'Puede crear empresas'), ('editar_empresa', 'Puede editar empresas'), ('autorizar_pago_diferido', 'Puede autorizar pago diferido')),
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='Empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
                'ordering': ['nombre'],
                'permissions': (('ver_areas_empresa', 'Puede ver áreas de su empresa'), ('crear_area', 'Puede crear áreas'), ('editar_area', 'Puede editar áreas')),
                'unique_together': {('nombre', 'empresa')},
            },
        ),
    ]
