# Generated by Django 4.2.24 on 2025-10-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nombre'], 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'permissions': (('autorizar_pago_diferido', 'Puede autorizar pago diferido'),), 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
