# Generated by Django 4.2.24 on 2025-10-20 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='allowed_encargado_roles',
            field=models.ManyToManyField(blank=True, related_name='areas_permitidas', to='Usuarios.role', verbose_name='Roles permitidos como encargados'),
        ),
        migrations.AddField(
            model_name='area',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='Empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='area',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Encargado del área'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(condition=models.Q(('es_area_financiera', True)), fields=('empresa',), name='unique_area_financiera_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(condition=models.Q(('es_area_abastecimiento', True)), fields=('empresa',), name='unique_area_abastecimiento_por_empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('nombre', 'empresa')},
        ),
    ]
