# Generated by Django 4.2.24 on 2025-10-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0002_alter_area_options_alter_empresa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre_contacto',
            field=models.CharField(default='Sin contacto', max_length=200, verbose_name='Nombre del contacto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=20, unique=True, verbose_name='NIT'),
        ),
    ]
