# Generated by Django 4.2.24 on 2025-10-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0003_empresa_nombre_contacto_alter_empresa_nit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'permissions': [('autorizar_pago_diferido', 'Puede autorizar pago diferido'), ('ver_todas_empresas', 'Puede ver todas las empresas')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
