# Generated by Django 4.2.24 on 2025-10-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0004_alter_empresa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='token_activacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Token de activación'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='token_expiracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración del token'),
        ),
    ]
