# Generated by Django 4.2.24 on 2025-10-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0005_empresa_token_activacion_empresa_token_expiracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
