# Generated by Django 4.2.24 on 2025-10-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0006_alter_empresa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='periodo_pago_dias',
            field=models.IntegerField(default=60, help_text='Máximo 60 días (2 meses)', verbose_name='Periodo máximo de pago (días)'),
        ),
    ]
