# Generated by Django 4.2.24 on 2025-10-09 17:57

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0007_empresa_periodo_pago_dias'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='area',
            managers=[
                ('activos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='empresa',
            managers=[
                ('activos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='es_area_financiera',
            field=models.BooleanField(default=False, help_text='Marca si esta área corresponde al departamento financiero', verbose_name='¿Es área financiera?'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(condition=models.Q(('es_area_financiera', True)), fields=('empresa',), name='unique_area_financiera_por_empresa'),
        ),
    ]
