# Generated by Django 4.2.24 on 2025-10-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0008_alter_area_managers_alter_empresa_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='es_area_abastecimiento',
            field=models.BooleanField(default=False, help_text='Marca si esta área corresponde al departamento de abastecimiento', verbose_name='¿Es área de abastecimiento?'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(condition=models.Q(('es_area_abastecimiento', True)), fields=('empresa',), name='unique_area_abastecimiento_por_empresa'),
        ),
    ]
