# Generated by Django 4.2.24 on 2025-10-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0009_area_es_area_abastecimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='area',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='empresa',
            managers=[
            ],
        ),
    ]
